# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.15.3' 

    - task: AzureCLI@2
      displayName: 'Ensure tfstate container exists'
      inputs:
        azureSubscription: 'AzureServiceConnectionWIF'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage container create \
            --account-name demostorageaccount197368 \
            --name prod-tfstate \
            --auth-mode login

    - task: Bash@3
      displayName: 'Clear ARM_* and TF_VAR_* variables'
      inputs:
        targetType: 'inline'
        script: |
          for var in $(env | grep ARM_ | cut -d= -f1); do
            unset $var
          done
          for var in $(env | grep TF_VAR_ | cut -d= -f1); do
            unset $var
          done
          echo "Environment cleaned"

    - task: TerraformTask@5
      displayName: Tf init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'AzureServiceConnectionWIF'
        backendAzureRmResourceGroupName: 'demo-resources'
        backendAzureRmStorageAccountName: 'demostorageaccount197368'
        backendAzureRmContainerName: 'prod-tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'
        commandOptions: '-reconfigure'

    - task: CmdLine@2
      displayName: 'Unset old TF_VAR variables'
      inputs:
        script: |
          unset TF_VAR_CLIENT_ID
          unset TF_VAR_CLIENT_SECRET
          unset TF_VAR_SUBSCRIPTION_ID
          unset TF_VAR_TENANT_ID
      
    - task: TerraformTask@5
      displayName: Tf fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'AzureServiceConnectionWIF'

    - task: TerraformTask@5
      displayName: Tf validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        backendAzureRmResourceGroupName: 'demo-resources'
        backendAzureRmStorageAccountName: 'demostorageaccount197368'
        backendAzureRmContainerName: 'prod-tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'

    - task: CmdLine@2
      displayName: Debug TF_VAR variables
      inputs:
        script: |
          echo "Listing TF_VAR_* variables..."
          env | grep TF_VAR_

    - task: TerraformTask@5
      displayName: Tf plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'AzureServiceConnectionWIF'
        commandOptions: '-out=$(Build.SourcesDirectory)/tfplanfile -lock=false'
      env:
        TF_VAR_prefix: demo
        TF_VAR_location: "Central India"
        
    - task: ArchiveFiles@2
      displayName: Archive files
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(Build.BuildId)-build'
        publishLocation: 'Container'